import DOMPurify from 'dompurify';

const SANITIZER_OPTIONS = {
    ADD_TAGS: ['iframe', 'audio', 'video', 'source'],
    ADD_ATTR: [
        'allow',
        'allowfullscreen',
        'class',
        'controls',
        'data-accordion',
        'data-align',
        'data-bg',
        'data-border-color',
        'data-block',
        'data-columns',
        'data-colwidth',
        'data-callout',
        'data-callout-type',
        'data-cols',
        'data-content-button',
        'data-display',
        'data-display-mode',
        'data-document',
        'data-embed-height',
        'data-embed-width',
        'data-file-size',
        'data-file-type',
        'data-filename',
        'data-language',
        'data-image-grid',
        'data-images',
        'data-variant',
        'data-title',
        'data-version',
        'data-mermaid-bg',
        'data-mermaid-border',
        'data-mermaid-code',
        'data-mermaid-theme',
        'data-mermaid-title',
        'data-open',
        'data-src',
        'data-summary',
        'displaymode',
        'download',
        'embedheight',
        'embedwidth',
        'filetype',
        'filesize',
        'frameborder',
        'loading',
        'rel',
        'src',
        'style',
        'target',
        'title',
        'type',
    ],
    FORBID_TAGS: ['script'],
    FORCE_BODY: true,
};

export function sanitizePostContent(content = '') {
    return DOMPurify.sanitize(content, SANITIZER_OPTIONS);
}
